### ISSUE TITLE
Any plans to put asv on PyPI?

### ISSUE THREAD

**Issue by embray** [spacetelescope/asv#109]
If there are any blockers to making a first "release" I'd be happy to take a look at them.  Just did a `pip install asv` hoping it might work :)

**Comment by pv** [comment]
Maybe it's time to consider release? Not necessarily 1.0, but at least 0.1 could be in place, given that basic functionality is there, and various usability issues/bugs have been ironed out.

**Comment by astrofrog** [comment]
Yes, we're already using this in production, so +1 to releasing! Release early, release often they say!

**Comment by mdboom** [comment]
Yeah -- hopefully I can find some time to do this today.

**Comment by mdboom** [comment]
I just put a release candidate up on PyPI.  Assuming it all works out well, I'll make a final release next week.

@embray, @pv, @astrofrog: Care to kick the tyres?
