### ISSUE TITLE
Long conda environment name

### ISSUE THREAD

**Issue by rhattersley** [spacetelescope/asv#169]
I'm trying to benchmark a project which has [several](https://github.com/SciTools/iris/blob/333a5fc8c31746412f684a2137f5cbe8e2685a49/conda-requirements.txt) dependencies. If I want asv to create a conda environment it seems I have to list the dependencies in the `matrix` entry of `asv.conf.json`. Unfortunately, *all* the entries in this matrix end up in the conda environment name. This makes the environment name too long for conda's automatic prefix re-writing(*).

How about only the multi-valued dependencies are used in the environment name instead?

*) For example:
```
> conda create -n this-is-way-too-long-for-the-automatic-prefix-stuff-to-cope-and-causes-an-exiciting-error-to-be-thrown udunits=2.*
Fetching package metadata: ...
Solving package specifications: .
Package plan for installation in environment /data/local/ithr/miniconda/envs/this-is-way-too-long-for-the-automatic-prefix-stuff-to-cope-and-causes-an-exiciting-error-to-be-thrown:

The following NEW packages will be INSTALLED:

    udunits: 2.2.17-4 scitools

Proceed ([y]/n)? 

Linking packages ...
Error: ERROR: placeholder '/home/travis/miniconda/envs/_build_placehold_placehold_placehold_placehold_place' too short in: udunits-2.2.17-4

```

**Comment by mdboom** [comment]
Thanks for the report.  Indeed, that is a problem, which I can confirm.  Will have to play with the best solution -- naming each environment after a particular instance of the dependency matrix is helpful if that matrix is later expanded and you don't want to throw out existing results.  But it may be that that doesn't matter for the environments themselves, only the results.

**Comment by pv** [comment]
Fixed in gh-181
