### ISSUE TITLE
Incremental benchmarking

### ISSUE THREAD

**Issue by rhattersley** [spacetelescope/asv#175]
Is there a way, or a plan for a way, to build up benchmarking results for a given machine across multiple invocations?

I'd like to be able to do something like the following and have the results combined.
```
$ asv run --bench my_slow_benchmark --quick
$ asv run --bench some_other_benchmark v3..v4
etc.
```
Currently the second invocation just throws away the results from the first. :unamused:

**Comment by mdboom** [comment]
Yeah, this should probably be made to work.  The `--bench` argument wasn't very well thought through and is really only useful for testing that certain benchmarks are working or to get quick one-off results.  The result-saving code pretty much assumes that you're running all of the benchmarks in a single invocation.  This may not be too difficult -- it should just be a matter of loading and existing results and merging the results into it rather than writing a new file each time.

**Comment by mdboom** [comment]
This is totally untested, but I think something like this should do the trick:

```diff
	Modified   asv/results.py
diff --git a/asv/results.py b/asv/results.py
index 93f140b..24af8ea 100644
--- a/asv/results.py
+++ b/asv/results.py
@@ -213,6 +213,10 @@ class Results(object):
         """
         path = os.path.join(result_dir, self._filename)
 
+        if os.path.exists(path):
+            old_results = self.load(path)
+            self.add_existing_results(old_results)
+
         util.write_json(path, {
             'results': self._results,
             'params': self._params,
@@ -248,6 +252,18 @@ class Results(object):
         obj._filename = os.path.join(*path.split(os.path.sep)[-2:])
         return obj
 
+    def add_existing_results(self, old):
+        """
+        Add any existing old results that aren't overridden by the
+        current results.
+        """
+        for key, val in six.iteritems(old.results):
+            if key not in self._results:
+                self._results[key] = val
+        for key, val in six.iteritems(old._profiles):
+            if key not in self._profiles:
+                self._profiles[key] = val
+
     def rm(self, result_dir):
         path = os.path.join(result_dir, self._filename)
         os.remove(path)
```

I may not have time to work this into a proper PR with a test, but maybe that helps show the way of what I'm thinking.

**Comment by pv** [comment]
Seems to be covered by gh-188 and gh-211
