### ISSUE TITLE
Explicitly select virtualenv or conda

### ISSUE THREAD

**Issue by cdeil** [spacetelescope/asv#178]
The docs say that currently the choice for `conda` is made automatically if that is on the PATH.
This doesn't seem to work for me.

So far I was using `virtualenv` and now I switched to `conda` using `rm -r env` and then `asv` still said it would try to use virtualenv "Creating virtualenv for py2.7-astropy-numpy-scipy." and then failed like this:
https://gist.github.com/cdeil/96eb55690b5288af2b61#file-gistfile1-txt-L6

Maybe it would be better to let the user make an explicit choice for virtualenv / conda via a configuration option? (This might also be better in case in the future other "backends" like e.g. Docker are added.)
And is this info which one was used stored somewhere in the results?

**Comment by mdboom** [comment]
I'm not opposed to this idea, by adding a new key to `asv.conf.json`.  This has caused other related issues as well in the past.
