### ISSUE TITLE
Document continuous

### ISSUE THREAD

**Issue by cdeil** [spacetelescope/asv#186]
I just noticed that the help for `asv continuous` doesn't show up in the docs:

* http://spacetelescope.github.io/asv/commands.html#asv-continuous
* https://github.com/spacetelescope/asv/blame/7d43df0d4f0e98c7eb49485c2f634a468b413ed9/asv/commands/continuous.py#L25

Maybe it's because of the newline after the `help=`?

**Comment by mdboom** [comment]
Hmm... it displays for me...

![screenshot](https://cloud.githubusercontent.com/assets/38294/5671759/88557888-9758-11e4-90a7-a7278db6d6a5.png)

**Comment by cdeil** [comment]
What I meant is that there's no `help` or `description` saying what this tool does.

This is because you use `subparsers.add_parser` and apparently this only shows what you put as `description` and for `continuous` you only put `help`.

I think it would be best to:
- Add a `description` for `continous` (all other commands have it).
- Somehow convince `argparse` to also show what's passed in `help`.

**Comment by mdboom** [comment]
Sorry I missed that.  Fix in #187.
