### ISSUE TITLE
Proper test repository data

### ISSUE THREAD

**Issue by pv** [spacetelescope/asv#233]
Currently the test suite uses live repositories as test data (asv and some other project for mercurial).
This is slightly awkward for writing tests since you need to find commits for existing test cases rather than just adding new test commits, and it's also somewhat slow due to cloning over the network.

It would be better if the test repositories were git and hg repositories, stored for example in zip files so that they are reproducible and can be manipulated without too much trouble. (You cannot store git repo in a git repo.)

**Comment by mdboom** [comment]
That's a good idea.

(Got a busy week or two ahead -- I'll self-assign if I find the time).
