### ISSUE TITLE
Problem with asv preview

### ISSUE THREAD

**Issue by stoiver** [spacetelescope/asv#247]
Just started having a play with asv and tried to use `asv preview`. 

I decided to use astropy-benchmarks. 

I ran
```
    asv publish
    asv preview
```

and viewed the results on firefox.

I obtained the error 

127.0.0.1 - - [17/Mar/2015 12:37:03] code 404, message File not found
127.0.0.1 - - [17/Mar/2015 12:37:03] "GET /graphs/Cython/arch-x86_64/branch/cpu-Intel(R)%20Core(TM)%20i7-3720QM%20CPU%20@%202.60GHz%20(8%20cores)/jinja2/machine-racoon/numpy-1.8/os-Mac%20OS-X%2010.9%20Mavericks/python-3.4/ram-8GB/io_ascii.time_rdb.RDBSuite.time_get_cols.json?_=1426556188401 HTTP/1.1" 404 -

when trying to get a view of the io_ascii.time_rdb.RDBSuite.time_get_cols benchmark.

I tracked the problem down to the name of the requested file. 

The command `asv publish` produces a file with `branch-master` in the file name instead of `branch`.

I moved the corresponding `branch-master` directory to `branch' and that fixed the problem.

So there seems to be an inconsisteny between `asv publish` and `asv preview`.

**Comment by pv** [comment]
This was fixed yesterday, so upgrading may help.

**Comment by stoiver** [comment]
Upgraded and the problem was fixed. Thanks
