### ISSUE TITLE
pip install wheel

### ISSUE THREAD

**Issue by argriffing** [spacetelescope/asv#248]
I assume this is somehow my fault, but when I was trying to run
`python runtests.py --bench-compare master sparse.Arithmetic`
as mentioned in https://github.com/scipy/scipy/tree/master/benchmarks, I hit a problem at the `pip install wheel` step on line https://github.com/spacetelescope/asv/blob/master/asv/plugins/virtualenv.py#L107 within `asv`.  The error is buried underneath a few layers of system/subprocess calls made by Python scripts, so it is kind of cryptic.  The `asv` package itself passes its internal tests on my system, but I have not tried to isolate the problem to use only `asv` scripts and not `scipy` scripts.

**Comment by pv** [comment]
What is the error message?

**Comment by argriffing** [comment]
This isn't all of the output, but it failed at the 'installing dependencies' step:
```
[...]/scipy$ python runtests.py --bench-compare master sparse.Arithmetic
· Fetching recent changes
· Fetching recent changes
· Creating environments
· Installing dependencies
```

at which point it gave tracebacks ending with this:
```
File "[...]/.local/lib/python2.7/site-packages/asv-0.1-py2.7.egg/asv/plugins/virtualenv.py", line 107, in install_requirements
    self._run_executable('pip', ['install', 'wheel'])
  File "[...]/.local/lib/python2.7/site-packages/asv-0.1-py2.7.egg/asv/plugins/virtualenv.py", line 122, in _run_executable
    os.path.join(self._path, 'bin', executable)] + args, **kwargs)
  File "[...]/.local/lib/python2.7/site-packages/asv-0.1-py2.7.egg/asv/util.py", line 295, in check_output
    cwd=cwd)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

Manually installing wheel didn't seem to help (I get the same error).  Maybe `asv` is not finding pip?  I see that `asv` uses `logging`, is there a way to enable these logs through the `runtests.py` wrapper in scipy?  Or maybe they are already being created somewhere?  Also `asv` seems to be using its virtualenv plugin.  According to `$ virtualenv --version` I have 12.0.7 (installed through pip on Ubuntu), but I'm not a virtualenv expert.  Most of my python modules have been installed through `$ pip install <package> --user` rather than through Ubuntu's package manager.

**Comment by pv** [comment]
Yes, looks like pip is not present in the virtualenv. Maybe the virtualenv is hosed, try `rm -rf benchmarks/env` to force asv to recreate it.

In particular, if you run `git clean`, it will currently hose up the virtualenv used by asv.
asv should be made smart enough to notice this.

**Comment by argriffing** [comment]
@pv Thanks, after `$ rm -rf benchmarks/env`, `$ python runtests.py --bench-compare master sparse.Arithmetic` has progressed beyond the 'installing dependencies' step.  It's currently 'Building for py2.7-Cython0.21.1-Tempita0.5.2-numpy1.8.2-six'.

**Comment by argriffing** [comment]
The command
`$ python runtests.py --bench-compare master`
has completed successfully after I worked around the problem by deleting `benchmarks/env`.

> In particular, if you run git clean, it will currently hose up the virtualenv used by asv.
asv should be made smart enough to notice this.

OK, I'll leave this issue open.
