### ISSUE TITLE
Is there currently a solution for using Webhooks with asv?

### ISSUE THREAD

**Issue by anderspitman** [spacetelescope/asv#271]
We'd like to have our server automatically run asv when master is pushed to on github. I didn't see anything in the asv codebase, but I thought asv or astropy might already have a daemon script or something similar in place for this?

**Comment by pv** [comment]
Can't speak for astropy, but I haven't seen such scripts. I'd guess most setups run it from cron.

**Comment by mdboom** [comment]
That's right.  For astropy, we run it nightly with cron.  If you don't need results immediately, it works pretty well (it still tests every new commit) and doesn't require setting up the test machine with open ports in the Internet.

**Comment by anderspitman** [comment]
Cool, thanks. I have a few more questions. I opened #272 to track them.
