### ISSUE TITLE
Command line option to select different asv.conf.json files

### ISSUE THREAD

**Issue by moorepants** [spacetelescope/asv#293]
It'd be nice to be able to change some settings in the conf file from the command line or to have the ability to select different conf files from the command line. Is this possible already?

**Comment by mdboom** [comment]
The config file can be specified from the command line using the `--config` option.

I'm going to close this, but feel free to reopen if I misunderstood the question.

**Comment by moorepants** [comment]
Thanks, I missed that.

**Comment by moorepants** [comment]
FYI, I do not see any reference to the `--config` option here: http://asv.readthedocs.org/en/latest/commands.html

**Comment by mdboom** [comment]
Thanks.  There seems to be a glitch in the generated docs (see #294), even though this is documented by `asv --help`.
