### ISSUE TITLE
Tests should use argument parser when calling commands

### ISSUE THREAD

**Issue by pv** [spacetelescope/asv#301]
Calling `Command.run` directly leaves the main code path that's actually used untested, cf. gh-298

It could be useful to test the whole stack and use the actual command line parser for launching commands in the tests. It's probably possible to write a small helper function that takes a conf object etc. plus command line arguments, and uses those to launch commands.

**Comment by qwhelan** [comment]
The outermost run method is ```Command.run_from_args()```, which looks looks like this (except ```update``` and ```quickstart```, which map to ```Command.run()```):
```python
    @classmethod
    def run_from_args(cls, args):
        from ..plugin_manager import plugin_manager
        conf = config.Config.load(args.config)
        for plugin in conf.plugins:
            plugin_manager.import_plugin(plugin)
        return cls.run_from_conf_args(conf, args)
```

The issues I see are:

 * Every test will be reading ```args.config``` from disk, which will require some tempdir creation/cleanup logic.

* More critically, every test will be importing anything included in ```conf.plugins```, which could make testing behavior dependent upon presence/absence of particular plugins tricky.

**Comment by pv** [comment]
I was thinking about a helper function that calls run_from_conf_args based on conf + argv.

**Comment by pv** [comment]
Another such bug found in gh-324.
gh-325 attempts to make it certain no more arise.
