### ISSUE TITLE
Windows timeout is not timeout from last output

### ISSUE THREAD

**Issue by pv** [spacetelescope/asv#319]
On windows, the `timeout` has a different meaning from unix currently, as it's timeout from start and not timeout since last output. The behavior should be made to match.

**Comment by jorisvandenbossche** [comment]
I just wanted to report that on Windows, building pandas times out (as it takes longer than 2 minutes, and manually increasing `timeout` in util.py solves it), but I assume the above is the cause of this?

**Comment by pv** [comment]
Yes, fairly sure that's the cause.

The easiest solution appears to be to move the blocking reads to threads reading 1 byte at a time.
Other option would be to use directly win32 async ("overlapped") i/o.

**Comment by pv** [comment]
Ok, MSDN states async io is not supported on anonymous pipes, so gh-320 is the only way to do this (short of rewriting subprocess module or using temporary files).
