### ISSUE TITLE
Specifying requirements depending on environment/OS

### ISSUE THREAD

**Issue by jorisvandenbossche** [spacetelescope/asv#322]
In trying to have an asv.conf.json file to be generic so that contributors don't have to adapt it, we have some problems in pandas.

As the required dependencies can in some cases depend on:
- OS: eg for building pandas on Window, there is an extra dependency when using conda (`libpython`)
- environment type: eg pytables is called tables for pip but pytables for conda. (which is more an issue with conda, but we have to deal with it)

It is just a question if this would be within scope to deal with such things. But I can understand the answer would quite possibly be: no, each contributor will have to adapt it to work for his/her machine.

E.g with conda yaml files, you can have lines to be specific for a certain OS using a kind of preprocessed selectors: http://conda.pydata.org/docs/building/meta-yaml.html#preprocessing-selectors

**Comment by pv** [comment]
I think this should be supported --- `asv.conf.json` is often checked in to vcs, so that it should be relatively static. Additionally, it would be useful to be able to override the specified environment type for example on command line.

This could along the lines:
```
"matrix": {
    "[environment=conda,platform=win32]libpython": [],
    "[python=3.*]six": [],
}
```
and possibly more generic syntax could be allowed,
```
"[platform=win32]matrix": {
    "libpython": [],
    "six": [],
},
"[platform=win32]pythons": ["2.7"],
"[platform=linux*]pythons": ["2.7", "3.4"],
```

**Comment by mdboom** [comment]
Yeah -- the whole dependency matrix thing is pretty minimal -- it's just the simplest thing to get something off the ground.  I think any changes we make to the "language" should also try to consider the other major shortcoming, namely no way to include or exclude specific combinations.  Travis-CI is fairly powerful in this regard.

I'm not sure I'm crazy about the additional metalanguage inside of dictionary keys, though.  I'd prefer something that was still parseable just from the tree of JSON objects.

**Comment by pv** [comment]
How about this? https://github.com/spacetelescope/asv/pull/329

This enables specifying platform/environment/python-dependent items in the requirement matrix, although you have to do it "backwards" (specify in matrix, but exclude non-applicable entries).
This may or may not be too clumsy for practice, comments welcome.

**Comment by pv** [comment]
gh-329 is probably ready now, assuming the approach is fine.

For Pandas, the config would read:
```
    "matrix": {
        "numpy": [],
        "Cython": [],
        "matplotlib": [],
        "sqlalchemy": [],
        "scipy": [],
        "numexpr": [],
        "pytables": [null, ""],
        "tables": [null, ""],
	"libpython": [null, ""],
        "openpyxl": [],
        "xlsxwriter": [],
        "xlrd": [],
        "xlwt": []
    },
    "exclude": [
	{"environment_type": "conda", "tables": ""},
	{"environment_type": "virtualenv", "pytables": ""},
	{"sys_platform": "(?!win32).*", "libpython": ""},
	{"sys_platform": "win32", "libpython": null},
	{"environment_type": "(?!conda).*", "libpython": ""},
    ],
```
or, alternatively listing each environment explicitly in includes,
```
    "matrix": {},
    "exclude": [
	// Include only the environments explicitly listed below 
	{}
    ],
    "include": [
        {"environment_type": "conda", "sys_platform": "win32", "python": "2.7",
	 "numpy": "", "Cython": "", "matplotlib": "", "sqlalchemy": "", "scipy": "",
         "numexpr": "", "pytables": "", "libpython": "", "openpyxl": "",
         "xlsxwriter": "", "xlrd": "", "xlwt": ""},
        {"environment_type": "conda", "sys_platform": "(?!win32).*", "python": "2.7",
	 "numpy": "", "Cython": "", "matplotlib": "", "sqlalchemy": "", "scipy": "",
         "numexpr": "", "pytables": "", "openpyxl": "",
         "xlsxwriter": "", "xlrd": "", "xlwt": ""},
        {"environment_type": "virtualenv", "python": "2.7",
	 "numpy": "", "Cython": "", "matplotlib": "", "sqlalchemy": "", "scipy": "",
         "numexpr": "", "tables": "", "openpyxl": "",
         "xlsxwriter": "", "xlrd": "", "xlwt": ""}
    ],
```

**Comment by pv** [comment]
Implemented in gh-329
