### ISSUE TITLE
`asv find` reads only first character from arguments

### ISSUE THREAD

**Issue by chris-b1** [spacetelescope/asv#324]
On win64, python 2.7 (anaconda), latest asv master.

    asv find 7ed0b26d..9687145e binary_ops.frame_multi_and_st.time_frame_multi_and_st

    · Error running C:\Program Files (x86)\Git\cmd\git.exe log --quiet --first-parent --format=format:%H 7

The problem seems to be [here](https://github.com/spacetelescope/asv/blob/master/asv/commands/find.py#L63) - I'm guessing the arguments are expected to be wrapped in some kind of sequence?  Locally at least, removing the `[0]` fixed the problem.

in find.py

        return cls.run(
            conf, args.range[0], args.bench[0],
            invert=args.invert, show_stderr=args.show_stderr,
            machine=args.machine
        )

**Comment by pv** [comment]
That looks like a bug left over from argument parsing refactoring.
Fix in gh-325
