### ISSUE TITLE
Packages installed with Pip, even when using Conda to create environments

### ISSUE THREAD

**Issue by msarahan** [spacetelescope/asv#327]
I'm probably misunderstanding exactly what's going on.  Is conda used to do anything more than provision the base environment?  I have a requirements.txt file, as well as a conda recipe and  an environment.yml.  It seems that only the requirements.txt file is used, and it feeds Pip?  The problem that precipitates this issue is that one (implicit) dependency of mine is Scipy, which tries to build from source on OSX, and barfs due to lack of Fortran compiler.  I want to pull from a binary source (conda repositories, ideally)

I'd like to use the environment.yml, which is consumed by conda-env - perhaps this is an additional backend?  I'm happy to implement this if it would be of value to others.

**Comment by pv** [comment]
Conda is used to provision the environment, based on the set of packages listed in `asv.conf.json`, so you should list the requirements you want to be present there.

Your project itself is however installed with pip, not with conda-build (cf gh-279).

**Comment by msarahan** [comment]
Beautiful, thank you!  This is a little clunky to have to keep the ASV conf and the other dependency lists in sync, but it works just fine.
