### ISSUE TITLE
Fetching from git-repo fails if remote named 'origin' does not exist

### ISSUE THREAD

**Issue by ankostis** [spacetelescope/asv#331]
The name of the git-repo 'origin' is hardcoded, 
eg. [``self._run_git(['fetch', 'origin'])``](https://github.com/spacetelescope/asv/blob/ceea6b366328b8bf8e53edd97b2c11a65f813ac2/asv/plugins/git.py#L87) 
so it fails if a project does not use this convention.

Reported against latest from master(@c07fdbf2da04a48334b4), under Windows.

**Comment by pv** [comment]
Did you run to an error, or is this based on inspecting the code?

When you do `git clone` doesn't it always assign `origin` as the name as the remote repository?
`asv` does the cloning by itself.

**Comment by pv** [comment]
If you are using an URL as the `repo` in the config, make sure there's no directory called *project* (the value for `project` specified in config).

**Comment by ankostis** [comment]
Yes i run it, and i got that err-message, and only then I peaked into the sources.

Thank you for the tip, indeed i was planning to embed and run the the asv.json from my project's sources, and, not unexpectedly, there is a sources folder with the same name as the project-name.

Now i'm having another problem which might be related that i'm using cygwin's `git` (instead of the mingw's `git`):

	· Cloning project
	· Error running d:\cygwin\bin\git.exe clone --mirror https://github.com/team/project d:\projdir\cprojname.asv
			STDOUT -------->

			STDERR -------->
			Cloning into bare repository 'd:\projdir\cprojname.asv'...
			/cygdrive/d/projdir/d:\projdir\projname.asv: No such file or directory

Should i open new issue or rename the title of this one?

**Comment by pv** [comment]
Yes, that's cygwin-related, please open a new issue for it.

**Comment by pv** [comment]
Note however that putting the asv.conf.json to your project's sources does work, if you tell it to use the local repository as the source, via `"repo": "."`

**Comment by ankostis** [comment]
Yes and no.
I get the same `cygwin` related error:

	Cloning into 'd:\projdir\env\77f2c104c7e2c3fba9eaad6360cdf4e8\project'...
				 fatal: '/cygdrive/d/projdir/d:\projdir' does not appear to be a git repository
				 fatal: Could not read from remote repository.
