### ISSUE TITLE
asv run does not use same python by default, but help message says it does

### ISSUE THREAD

**Issue by jorisvandenbossche** [spacetelescope/asv#337]
The help message for `--python` says:

>  --python PYTHON      
> Specify a Python interpreter in which to run the
                        benchmarks. **By default, uses the same Python
                        interpreter that asv is using**. It may be an executable
                        to be searched for on the $PATH, an absolute path, or
                        the **special value "same" which will use the same
                        Python interpreter that asv is using**. This "same"
                        interpreter must have the benchmarked project already
                        installed, including its dependencies. A specific
                        revision may not be provided when --python is
                        provided. It may also be any string accepted by any of
                        the environment plugins. For example, the conda plugin
                        accepts "2.7" to mean create a new Conda environment
                        with Python version 2.7.

(emphasize mine) so it says it will use the same python by default. However, I don't think this is true.

Probably this has changes here: https://github.com/spacetelescope/asv/pull/239
The problem is that the help message is reused for different commands (`run` and `dev`, but that they use a different default)

**Comment by pv** [comment]
Adding the `environment_type` config setting (07cd36a7) seems to have broken specifying a python executable to use; only `python=same` results to using ExistingEnvironment.

**Comment by pv** [comment]
The right thing to do is probably to make also the environment type selectable on command line,
in addition to the python version. Then `--environment=existing --python=/usr/bin/python` works.

**Comment by jorisvandenbossche** [comment]
@pv maybe I was not fully clear, but I just wanted to report a documentation issue. I am fine with the behaviour of `asv run`, but the docs seem to say that its default behaviour is identical to using `--python same`, which is not true I think.

**Comment by pv** [comment]
Yes --- however, the part of the message talking about specifying a Python executable is also incorrect currently.

**Comment by pv** [comment]
In gh-340
