### ISSUE TITLE
hglib failures on travis

### ISSUE THREAD

**Issue by pv** [spacetelescope/asv#345]
hglib is raising a ServerError on travis-ci in `test_repo_hg`. No code changes in asv, however.

Probably python-hglib==1.5 is incompatible with the Mercurial version 3.6 released 2015-11-01. Maybe there's an upgraded python-hglib; .travis.yml pins it to a somewhat older version.

https://travis-ci.org/spacetelescope/asv/jobs/89088436#L296

**Comment by mdboom** [comment]
@MatthewTurk: Are you plugged into the hglib/mercurial world?  Any idea what might be going on here?  (I tried updating Travis to use the latest of both mercurial and hglib in #349, but that didn't work).

**Comment by pv** [comment]
Note that the failure is in the part `# check recovering from corruption` of the test.
`plugins/mercurial.py:Hg` probably needs to be changed so that it catches ServerError in addition to `hglib.error.CommandError`.

**Comment by ngoldbaum** [comment]
The latest version of python-hglib is 1.9. I would try updating.
