### ISSUE TITLE
Documentation doesn't explicitly say that it builds the project using setup.py

### ISSUE THREAD

**Issue by edisongustavo** [spacetelescope/asv#360]
I'm experimenting with airspeed velocity and I followed the documentation at http://asv.readthedocs.org/en/latest/using.html#setting-up-a-new-benchmarking-project

**Installing**:

```bash
git clone git@github.com:spacetelescope/asv.git
cd asv
python setup.py install
```

**Creating sample project:**

```bash
mkdir asv_experiments
cd asv_experiments
asv quickstart
# answer 'y'
vim asv.conf.json
# I edited the file and set "environment_type" : "conda"
# Notice that in this case the file contains this key: "repo": ".",

asv run
```

I got the following error: 

```bash
/home/muenz/Projects/asv_experiments/.asv/env/15347c5ee07fdae3ab84bf63d7449371/bin/python: can't open file 'setup.py': [Errno 2] No such file or directory
```

I've debugged the `asv run` code and found out it runs `python setup.py build` on the checked-out project code (the one checked-out by the key "repo").

I didn't find any mention to this on http://asv.readthedocs.org/en/latest/using.html#setting-up-a-new-benchmarking-project, so maybe there should be a mention to it.

Should the "quickstart" take care of this too?

**Comment by mdboom** [comment]
`quickstart` doesn't change or have access to the project being tested, so it can't add a `setup.py` file.

I agree, though, that it's worth mentioning in the docs that the project being tested must be pip-installable, which implies it must have a setup.py.

**Comment by edisongustavo** [comment]
> the project being tested must be pip-installable

Do you think that this requirement could be relaxed?

I ask because I was experimenting with ASV with the projects in my company and they're not pip-installable, so I had to do some workarounds (didn't finish) in order to evaluate ASV.

**Comment by pv** [comment]
asv must be able to install and uninstall the projects reliably, and in Python space I don't know of approaches besides pip that do this. Outside Python, I'm not sure how reliably eg cmake or automake deal with `make uninstall`.

If you know how to do it for your build system, it probably is possible to write an asv user-side plugin inheriting from the virtualenv one.

**Comment by arne-cl** [comment]
Is it possible to use `asv` with packages that are pip-installable but only via `pip install -r requirements.txt`?
