### ISSUE TITLE
Plain "asv run" always using "master" is inconsistent.

### ISSUE THREAD

**Issue by johntyree** [spacetelescope/asv#364]
I was expecting `asv run` to run the benchmarks using the branches listed in `asv.conf.json`. Poking around in docs and source indicates that [this is not the case](https://github.com/spacetelescope/asv/blob/master/asv/commands/run.py#L151).

Why does the default behavior differ from `ALL` and `NEW`? Particularly since the default value of `conf.branches` is `["master"]` anyway.

**Comment by pv** [comment]
There's probably no real reason for this --- the branch support was added afterward, so it seems this was just missed.
