### ISSUE TITLE
Order by commit log instead of date

### ISSUE THREAD

**Issue by philpep** [spacetelescope/asv#390]
Hello,

Commits are ordered by date for both graph and regression detection. In a workflow with merges (rebase + fast forward merge for instance) or cherry-picked commits, the commit date is not monotonic along the commit log.

I'm considering fixing the publish command to reorder commits as they appear in the commit log, but this will be a big breaking change. I wonder if you have others ideas to fix or workaround this issue ?

Thanks!

**Comment by philpep** [comment]
I have a working WIP patch in https://github.com/philpep/asv/commits/mercurial that I'm currently trying to split it in several incremental proper and well tested commits.

My current implementation remove completely commit date handling from asv and is based only on commit order. Thus there is no more dates on X axis and no dates shown in the regression page. Maybe I could keep both a

**Comment by mdboom** [comment]
I think I see utility for both orderings -- commit order and date.  Date is particularly useful as it relates to release tags and just overall project "velocity".  Adding another mapping to the index.json from commit "order id" to hash should be enough for the frontend to then deal accordingingly (by switching an option in the UI).
