### ISSUE TITLE
git repo with submodules

### ISSUE THREAD

**Issue by alimanfoo** [spacetelescope/asv#414]
I have my code in a git repository with submodules, is there any way to get ASV to do a recursive clone or update submodules so that they are present and in line with whatever commit is being benchmarked?

**Comment by pv** [comment]
That's probably not supported now (which is an oversight).

**Comment by pv** [comment]
Should be fixed in #426

**Comment by alimanfoo** [comment]
Cool, thanks very much, will try it out.

On Friday, June 10, 2016, Pauli Virtanen <notifications@github.com> wrote:

> Should be fixed in #426 <https://github.com/spacetelescope/asv/pull/426>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/spacetelescope/asv/issues/414#issuecomment-225272290>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAq8QlWFkItB0ddltz6WlmuJDTBDO8Awks5qKbjegaJpZM4IbIJl>
> .
>


-- 
Alistair Miles
Head of Epidemiological Informatics
Centre for Genomics and Global Health <http://cggh.org>
The Wellcome Trust Centre for Human Genetics
Roosevelt Drive
Oxford
OX3 7BN
United Kingdom
Email: alimanfoo@googlemail.com <alimanfoo@gmail.com>
Web: http://purl.org/net/aliman
Twitter: https://twitter.com/alimanfoo
Tel: +44 (0)1865 287721
