### ISSUE TITLE
Copyright information and supported python versions

### ISSUE THREAD

**Issue by MSeifert04** [spacetelescope/asv#421]
The [documentation](http://asv.readthedocs.io/en/latest/installing.html) contains a copyright note at the bottom stating that the copyright is 2013. I'm no expert but generally pages (like github) either list the current year (2016) or the extend of the copyright (2013-2016). Maybe it was just forgotten to alter it, or maybe altering it is unnecessary.

Also the supported python versions (http://asv.readthedocs.io/en/latest/installing.html) don't contain python 3.5. A quick search in the package revealed that there was at least a PR to make it py3.5 compatible #399 and even if my ``python setup.py test`` contained two failures (see also [the gist containing the test log](https://gist.github.com/MSeifert04/1850d3da5213061588c94d27422ec607)) I had no problems running it on python 3.5. So maybe it could be included on the documentation page.

Besides these issues: What a great package - Thank you!

**Comment by philpep** [comment]
Hi, the relevant informations on the failed tests are:

```
E           asv.util.ProcessError: Command 'C:\Program Files\Git\bin\git.exe add setup.py' returned non-zero exit status 128

            STDERR -------->
            fatal: Unable to write new index file
```

Other `test_regression_*` from `test_publish.py` run the same commands with success. Looks like out of space on `C:\\Users\\-\\AppData\\Local\\Temp` or a git bug. The failure is reproducible ?

**Comment by MSeifert04** [comment]
No, they are not really reproducible. The next test produced another failure (during another test-function): https://gist.github.com/MSeifert04/b97458341d87c15c4e27cb81c97f04e2

If it's some git bug or out of space problem it's not really important - I didn't plan on contributing. I just ran the tests to verify that it works with python 3.5 (given that it wasn't listed as supported python distribution). 

Seems like something's wrong on my machine. :disappointed:

Thank you for the fast response @philpep

**Comment by pv** [comment]
Docs updated in gh-427. IANAL, but afaik the copyright notices are only informative, and not even required under Berne convention.
