### ISSUE TITLE
Tags shown as vertical lines but not labelled

### ISSUE THREAD

**Issue by astrofrog** [spacetelescope/asv#443]
Currently, tags are shown as vertical lines:

http://www.astropy.org/astropy-benchmarks/#time_table.TimeTable.time_vstack

but these lines are not labelled, so it's not easy to know which is which. Could we make it for example that when hovering over a line, the tag is shown?

**Comment by pv** [comment]
The labels are on the top of the graph, but they tend to overlap.

**Comment by astrofrog** [comment]
Huh that's weird, I don't see them at all:

<img width="820" alt="screen shot 2016-06-19 at 08 53 48" src="https://cloud.githubusercontent.com/assets/314716/16176076/675803ec-35fb-11e6-8f6a-0e73d033a427.png">

Could it be a javascript version?

**Comment by pv** [comment]
Should look like this (Firefox, and the same on Chrome)
![kuvakaappaus 2016-06-19 14-38-24](https://cloud.githubusercontent.com/assets/35046/16177395/26494f92-362c-11e6-8936-b40946c3e57e.png)

**Comment by astrofrog** [comment]
I'm using Safari, and it doesn't work in Chrome either.

**Comment by pv** [comment]
Can you try resizing the browser window to different aspect ratios?
Maybe the labels get cut off in some cases.

**Comment by astrofrog** [comment]
@pv - I tried resizing in various ways, but no luck

**Comment by pv** [comment]
gh-470 maybe fixes it (can't repro the bug however)?

**Comment by pv** [comment]
@astrofrog: if you have time, could you check if gh-470 fixes it?

**Comment by astrofrog** [comment]
@pv - sorry for the delay, I'll test this today and close the issue if it works.

**Comment by astrofrog** [comment]
@pv - yes, it works for me now, thanks!
