### ISSUE TITLE
multiprocessing support

### ISSUE THREAD

**Issue by humm** [spacetelescope/asv#454]
I am using `multiprocessing.imap` to launch concurrent work process to run my algorithms, and airspeed velocity seems only to track the cpu time of the main process, rendering the benchmark result unusable (the program runs in ~1min, but asv reports 120ms). Is it normal, did I miss something? Is it a fundamental limitation of airspeed velocity?

**Comment by pv** [comment]
Please see the documentation of the `timer` attribute in 
https://asv.readthedocs.io/en/latest/writing_benchmarks.html#timing

**Comment by humm** [comment]
Thanks! It's exactly what I needed.
