### ISSUE TITLE
asv run -E existing:same not working: "No environments selected"

### ISSUE THREAD

**Issue by jorisvandenbossche** [spacetelescope/asv#458]
When running:

```
asv run --environment existing:same
```

to run the benchmarks using the current python where asv is installed, I get the message:
```
· No environments selected
```

I am running asv master (`asv 0.2.dev993+cfe55f27`) on Windows. 
Is there something I am doing wrong? (I run the command from the directory where the asv config file lives)

**Comment by pv** [comment]
Worksforme on linux. Maybe add `import pdb; pdb.set_trace()` on 
asv/environment.py before line 564, and check why it doesn't find your 
Python executable?

**Comment by pv** [comment]
Probably the `sys.executable` of your Python executable has forward 
slashes, not os.path.sep?

**Comment by jorisvandenbossche** [comment]
That sounds plausible, will check with the trace now

**Comment by jorisvandenbossche** [comment]
It's not the slashes, and putting the tracer there didn't get there, but I think I found the problem: in `iter_requirement_matrix`, it is checked if the rules match. And because for pandas we have in the 'exclude' section of the config rules about libpython that has to be available for windows, it decides the rules match, break out of the loop and do not regard the current environment (https://github.com/spacetelescope/asv/blob/master/asv/environment.py#L77)

**Comment by jorisvandenbossche** [comment]
But as far as I understand, if you are using `existing:same`, it should not test any rules?

If I comment out the 3 lines related to libpython selection (https://github.com/pydata/pandas/blob/master/asv_bench/asv.conf.json#L82), it works. But, it runs the same benchmark multiple times with seemingly the same environment

**Comment by pv** [comment]
The pandas rules are slightly wrong, they exclude all non-conda 
environments on win32. Cf. 
https://github.com/pv/pandas/commit/d74b08a23aadd74794ffe71ebff07db3e1be621a 
(didn't get around to submitting a PR...)
.
The include/exclude interaction with -E seems a bit unintuitive currently.

**Comment by jorisvandenbossche** [comment]
@pv Thanks, that indeed works without commenting out the lines.

But, I still get multiple environments:

```
(devel) C:\Users\vdbosscj\Scipy\pandas-joris\asv_bench>asv run -E existing:same -b time_dtype_infer_datetime64

· Discovering benchmarks
· Running 4 total benchmarks (1 commits * 4 environments * 1 benchmarks)
[  0.00%] ·· Building for existing-pyC:_Anaconda_envs_devel_python.exe
[  0.00%] ·· Benchmarking existing-pyC:_Anaconda_envs_devel_python.exe
[ 25.00%] ··· Running ...infer_datetime64.time_dtype_infer_datetime64   13.24ms
[ 25.00%] ·· Building for existing-pyC:_Anaconda_envs_devel_python.exe
[ 25.00%] ·· Benchmarking existing-pyC:_Anaconda_envs_devel_python.exe
[ 50.00%] ··· Running ...infer_datetime64.time_dtype_infer_datetime64   13.04ms
[ 50.00%] ·· Building for existing-pyC:_Anaconda_envs_devel_python.exe
[ 50.00%] ·· Benchmarking existing-pyC:_Anaconda_envs_devel_python.exe
[ 75.00%] ··· Running ...infer_datetime64.time_dtype_infer_datetime64   13.05ms
[ 75.00%] ·· Building for existing-pyC:_Anaconda_envs_devel_python.exe
[ 75.00%] ·· Benchmarking existing-pyC:_Anaconda_envs_devel_python.exe
[100.00%] ··· Running ...infer_datetime64.time_dtype_infer_datetime64   13.38ms
```

This is (I think) because it still sees the two different versions of tables and pytables and so creates a matrix of 4 environments with the different combinations. 

I now quickly solved this for me with bypassing `iter_requirement_matrix` when using existing:same :

```
        if env_type == "existing" and pythons == ["same"]:
            cls = get_environment_class_by_name(env_type)
            yield cls(conf, pythons[0], {})
        else:
            for requirements in iter_requirement_matrix(env_type, pythons, conf, process_includes):
                ...
```

but I don't think this is a very clean solution :-)

**Comment by jorisvandenbossche** [comment]
@pv After changing the exclude config as you suggested, this now works correctly, so only 1 envrionment. So closing this!
