### ISSUE TITLE
Allow dependency to be installed from git

### ISSUE THREAD

**Issue by postelrich** [spacetelescope/asv#494]
Would be great to also support setting a dependency to install pip install from git like the below.  Some projects are built in tandem and only work with specific dependencies that may only be available as commits.

`pip install git+https://github.com/repo/project.git`

I found that this can already be done by setting the `matrix` config in asv.conf.json to:

```
{
  'pip+git+https://github.com/repo/project.git': []
}
```

but the directory structure for results gets messed up.  It causes the results to get put in nested directories presumably because of a split on `/` is done on the key.  This results in asv not able to find `machine.json` when doing `asv publish`.

**Comment by postelrich** [comment]
One simple solution would be to have it look in parent directories until it finds `machine.json`.  Not sure what the reasons would be against that.  

Also of course want to properly handle this case by appropriately creating the directories instead of splitting on the url.

**Comment by pv** [comment]
environment.py:get_env_name should probably escape/mangle the
requirement names in some way. Pull requests with tests accepted.

**Comment by postelrich** [comment]
@pv Sure I'll take a look at that.  One extra thing noted, `run EXISTING --skip-existing-successful` always runs in this case. Just something else to check when fixing this bug.
