### ISSUE TITLE
takes very long to run a very quick/short benchmark

### ISSUE THREAD

**Issue by yarikoptic** [spacetelescope/asv#497]
to try asv I have decided first to benchmark our import/basic invocation times.  For that I have created following suite

```python
import os
import sys
import os.path as osp

from subprocess import call


class StartupSuite:
    """
    Benchmarks for datalad commands startup
    """

    def setup(self):
        # we need to prepare/adjust PATH to point to installed datalad
        # We will base it on taking sys.executable
        python_path = osp.dirname(sys.executable)
        self.env = os.environ.copy()
        self.env['PATH'] = '%s:%s' % (python_path, self.env.get('PATH', ''))

    def time_help_np(self):
        call(["datalad", "--help-np"], env=self.env)
        
    def time_import(self):
        call([sys.executable, "-c", "'import datalad'"])
```

both --help invocation and import do not take long, and that is where problem comes -- I guess there is a notable overhead of `timer.timeit()` invocation, which probably takes more than my benchmark.  So even though `timing` reported by it is small (a few ms), it takes a really while to actually run `timer.timeit()`, here is a dump from pdb session where I stopped right before executing the timeit:
```
> /home/yoh/proj/datalad/datalad/venvs/dev/local/lib/python2.7/site-packages/asv/benchmark.py(532)run()
-> timing = timer.timeit(number)
(Pdb) import time; 
(Pdb) t0 = time.time(); timing = timer.timeit(number); print("took %s", time.time()-t0); print("Timing: ", timing)
('took %s', 7.543498992919922)
('Timing: ', 0.46742375799999997)
(Pdb) p number
1000
```
So if timing of 1,000 invocations was 460ms, overall timing took for timer.timeit is over 7 sec.  And then in next loop it would be 10,000 ;-) making the whole thing take REALLY long time to complete.  I guess there should be some account for a wall clock time here as well

**Comment by pv** [comment]
For import benchmark, you need to set the `timer` attribute, since the
default one iirc doesn't count subprocess time.
