### ISSUE TITLE
teardown_cache is "exampled" but not implemented

### ISSUE THREAD

**Issue by yarikoptic** [spacetelescope/asv#511]
#277 added support for `setup_cache` and I see example also of the matching `teardown_cache` in test/benchmark/cache_examples.py but unfortunately support for it is actually not implemented. So if I am creating some reusable by all benchmarks resource (e.g. temporary file), the only way I could get rid of it whenever I am done I guess is to use atexit callback

**Comment by pv** [comment]
Temporary files can be created in cwd, which will be cleared up when the 
cache is cleared. There's no teardown_cache.

**Comment by yarikoptic** [comment]
Actually atexit workaround doesn't even work since gets invoked also after running `setup_cache` :-/  so I guess the only way to fix it is just to implement support for it :-/

**Comment by yarikoptic** [comment]
thanks @pv -- I will check it out

**Comment by yarikoptic** [comment]
ha -- whenever `setup_cache` runs under temp directory, setup and teardown -- under original current... heh, good to know before removing something with relative paths of possible value ;)
