### ISSUE TITLE
Nix environment plugin

### ISSUE THREAD

**Issue by Warbo** [spacetelescope/asv#531]
Hello, I've written [a Nix asv plugin](https://github.com/warbo/asv-nix) which you may be interested in. It uses [Nix](https://nixos.org/nix) instead of virtualenv/conda/etc. This is useful to me, and may be to others. I'd welcome any feedback, etc.

Nix is a build/packaging system with lots of nice features, but the main advantage to using it over asv's built-in environments is that we can use arbitrary, non-Python projects and dependencies. So far I've used it successfully on [a Racket project](https://github.com/warbo/theory-exploration-benchmarks) and am currently porting across [a Haskell project](https://github.com/warbo/haskell-te).

Since this has been a "scratch my own itch" project, it's a bit rough around the edges. In particular, I've added some extra config options (so we can specify *how* to build packages, rather than just naming them) and I've ignored all of the Python-specific stuff, like "pip+..." dependencies, specifying different Python versions, etc. since a) I've not needed it and b) it doesn't seem necessary, since all dependencies (including Python) are specified in a Nix expression, and as such can be fetched/built/generated/etc. in arbitrary ways.

If there are any obvious improvements/fixes to be made I'd appreciate the extra eyeballs and experience (I've not used Python in anger for about a decade!)

**Comment by pv** [comment]
Looks nice.

However, I don't think this should be merged to the asv mainline --- I don't use nix myself and hadn't heard about it before, and don't want to spend time maintaining the plugin. I think it's best to keep it in a separate package for the present.
