### ISSUE TITLE
Emitting multiple outputs?

### ISSUE THREAD

**Issue by Warbo** [spacetelescope/asv#532]
Hello, I've got a use-case which I can't figure out the best approach for, or whether it's feasible in asv as it stands.

I have some benchmarks parameterised by a "size". Each one runs a subprocess, using that size as an argument. One benchmark records the wall-clock time taken, whilst two tracking benchmarks return values taken from the output. Hence for each size, the subprocess runs three times.

Since the subprocess takes a non-trivial amount of time, it would be nice if it were only run once per size, and each of these benchmarks took its result from this single run (with the time turning into a tracking benchmark). I think a parameterised `setup_cache` would work, but the docs say this isn't implemented.

What would the best approach be here? For example, I could check the current directory for an existing result of this size, and generate+save it if not found. Would the way asv handles temporary directories make this feasible?

**Comment by pv** [comment]
IIRC there are duplicate issues on this point.

**Comment by pv** [comment]
But yes, parameterized setup_cache works. (If the docs say otherwise, I 
think they are incorrect --- on which page is the claim in?)

**Comment by pv** [comment]
Ah sorry, indeed setup_cache is not parameterized, but I think this is 
by design, not because it's not implemented.
.
However, you can precompute the results in a for loop in setup_cache.

**Comment by Warbo** [comment]
> However, you can precompute the results in a for loop in setup_cache

Ah, I was wondering if there were a way to avoid that, since it would cause a bunch of up-front work; but I suppose I can spit progress to stderr, and the benchmarks themselves would be finish instantly aferwards. Thanks.
